<?php
/**
 * @package KetShop
 * @copyright Copyright (c)2012 - 2016 Lucas Sanner
 * @license GNU General Public License version 3, or later
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');

//Check if the utility session array has already been created by setPayment
//controller function. 
$session = JFactory::getSession();
$utility = $session->get('utility', array(), 'ketshop'); 
?>

<div class="blog" id="ketshop-payment">


<?php if(!empty($utility) && !empty($utility['plugin_output'])) : ?>

  <?php echo $utility['plugin_output']; //Display the html output generated by plugins.  ?>

<?php else : //Display the available payment modes. ?>

  <h1 class="main-title"><?php echo JText::_('COM_KETSHOP_CHOOSE_PAYMENT_MODE_TITLE'); ?></h1>

  <?php $paymentPlugins = ShopHelper::getPaymentModes();//Get the available payment plugins.?>

  <form action="<?php echo JRoute::_('index.php?option=com_ketshop&task=payment.setPayment');?>"
	method="post" id="ketshop_payment">
  <?php

   foreach($paymentPlugins as $id => $paymentPlugin) :
     $checked = '';
     if(!$id) { //Check by default the first entry found.
       $checked = 'checked="checked"';
     } ?>

     <div class="group">
      <h2><?php echo $paymentPlugin->name; ?></h2>
     <input type="radio" class="payment-rb" name="payment" value="<?php echo $paymentPlugin->plugin_element; ?>" <?php echo $checked; ?> />
       <?php echo $paymentPlugin->description; ?>
     </div>

  <?php endforeach; ?>

  <input id="submit-button" class="btn" type="submit" value="<?php echo JText::_('COM_KETSHOP_PAY'); ?>" />

  </form>
<?php endif; ?>

</div>

